version: '2.1'

networks:
  kursovay-net:
    driver: bridge

services:

  postgres:
    container_name: postgresdb
    image: postgres:13.3
    environment:
      POSTGRES_DB: "apidb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secretochka2442"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      #volumes:
      #  - ./pgdata/:/var/lib/postgresql/data
      #- ../Init Database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d apidb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - kursovay-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "scretochka@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "secretochka2442"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./backups:/home/pgadmin/backups
    ports:
      - "5050:80"
    networks:
      - kursovay-net

  api:
    container_name: api
    image: secretochka/api-kursovay:2.2
    ports:
      - "49151:80"
    networks:
      - kursovay-net

  node_client:
    container_name: node_client
    image: secretochka/node-api-client:1.0
    ports:
      - "49152:3000"
    networks:
      - kursovay-net
